FROM snkattck/desktop:latest
RUN sudo pacman --noconfirm -Syy && \
    sudo pacman --noconfirm -Su && \
    sudo pacman --noconfirm -S \
        julia \
        openblas \
        r \
        tensorflow \
        python-matplotlib \
        python-scikit-learn && \
    sudo pacman --noconfirm -Scc