FROM snkattck/desktop:latest
RUN sudo pacman --noconfirm -Syy && \
    sudo pacman --noconfirm -Su && \
    sudo pacman --noconfirm -S \
        emacs && \
        code && \
        vim && \
    sudo pacman --noconfirm -Scc